name: control_style
description: Adds extra decoration to Flutter text fields and buttons.
version: 0.0.1
repository: https://github.com/astoniocom/control_style
issue_tracker: https://github.com/astoniocom/control_style/issues
homepage: https://astoniocom.github.io/control_style/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
