name: control_style
description: Applies additional decoration to Flutter-based text fields, buttons and other controls. This allows for better interface customisation.
version: 0.0.2
repository: https://github.com/astoniocom/control_style
issue_tracker: https://github.com/astoniocom/control_style/issues
homepage: https://astoniocom.github.io/control_style/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
